spring:
  application:
    name: ybwx-uaa
  security:
    user:
      name: ybwx
      password: ybwx
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://demo.mysql.cn:3306/demo?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
    username: root
    password: root

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15  # 服务过期时间
    lease-renewal-interval-in-seconds: 5      # 服务实例刷新时间
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
#security:
#  oauth2:
#    resource:
#      id: resource-id
#      service-id: resource