spring:
  application:
    name: ybwx-stock
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  security:
    user:
      name: ybwx
      password: ybwx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://demo.mysql.cn:3306/demo?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8110

mybatis:
  mapper-locations: classpath:/mybatis/*.xml

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1  # 服务过期时间
    lease-renewal-interval-in-seconds: 1     # 服务实例刷新时间
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    eviction-interval-timer-in-ms: 15000       # 剔除服务时间
  client:
    register-with-eureka: true

security:
  oauth2:
    client:
      client-id: client_1
      client-secret: client_1
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me # 自定义的用户信息地址