spring:
  application:
    name: ybwx-manager-admin
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql0.res.nuobei.cn:3306/ybwx_admin?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
    username: ybwxdev
    password: ybwx@dev
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 5
    host: 192.168.5.203
    port: 6380
    key-prefix: manager-admin

mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    cache-enabled: true

server:
  port: 8090
  servlet:
    context-path: /admin

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15  # 服务过期时间
    lease-renewal-interval-in-seconds: 5      # 服务实例刷新时间
    status-page-url-path: ${server.servlet.context-path:/admin}/actuator/info
    health-check-url-path: ${server.servlet.context-path:/admin}/actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    eviction-interval-timer-in-ms: 15000       # 剔除服务时间
  client:
    register-with-eureka: true