spring:
  application:
    name: ybwx-order
  security:
    user:
      name: ybwx
      password: ybwx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://demo.mysql.cn:3306/demo?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:/mybatis/*.xml

server:
  port: 8090

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15  # 服务过期时间
    lease-renewal-interval-in-seconds: 5      # 服务实例刷新时间
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true

feign:
  okhttp:
    enabled: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me # 自定义的用户信息地址