spring:
  application:
    name: ybwx-manager-admin
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    master:
      url: jdbc:mysql://mysql0.res.nuobei.cn:3306/ybwx_admin?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
      username: ybwxdev
      password: ybwx@dev
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true      # 新版本MySQL支持服务器端准备，开启能够得到显著性能提升
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    slave:
      url: jdbc:mysql://127.0.0.1:3306/ybwx_admin?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      connectionTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 5
      username: root
      password: root
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true      # 新版本MySQL支持服务器端准备，开启能够得到显著性能提升
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 5
    host: 192.168.5.203
    port: 6380
    key-prefix: manager-admin

mybatis:
  configuration:
    cache-enabled: true

server:
  port: 8110
  servlet:
    context-path: /demo

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15  # 服务过期时间
    lease-renewal-interval-in-seconds: 5      # 服务实例刷新时间
    status-page-url-path: ${server.servlet.context-path:/admin}/actuator/info
    health-check-url-path: ${server.servlet.context-path:/admin}/actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    eviction-interval-timer-in-ms: 15000       # 剔除服务时间
  client:
    register-with-eureka: true